- name: "Introduction"
  link: "/introduction"
- name: "Eyewitnesses"
  link: "/eyewitnesses"
- name: "Style & Handling"
  link: "/style-handling"
- name: "Provenance"
  link: "/provenance"
- name: "The debate so far"
  link: "/debate"
- name: "Our aims"
  link: "/our-aims"
- name: "Resources"
  link: "/resources"